[project]
name = "mlax"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datasets>=3.6.0",
    "equinox>=0.12.2",
    "jax>=0.6.0",
    "jaxtyping>=0.3.2",
    "tqdm>=4.67.1",
    "wandb>=0.19.11",
]
